appVersion: v1
kind: Service
metadata:
  name: nextjs-service
spec:
  type: NodePort
  selectors:
    app: nextjs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30007
